# core/tree_data.py

# Структура: "Branch Name": [ ("Code", "Talent_ID"), ... ]
# Code - это номер на картинке (например, "3.2")
# Talent_ID - это id из TALENT_REGISTRY (например, "defense_zafu")

SKILL_TREE = {
    "Ветка 1: Искажение": [
        {"code": "1.1", "id": "keep_it_together", "req": None},
        {"code": "1.2", "id": "center_of_balance", "req": "keep_it_together"},
        {"code": "1.3", "id": "tea_master", "req": "center_of_balance"},
        {"code": "1.4", "id": "mind_power", "req": "tea_master"},
        {"code": "1.5", "id": "peak_sanity", "req": "mind_power"},
        {"code": "1.6", "id": "psychic_strain", "req": "peak_sanity"},
        {"code": "1.7", "id": "unbearable_presence", "req": "psychic_strain"},
        {"code": "1.8", "id": "emotional_storm", "req": "unbearable_presence"},
        {"code": "1.9 A", "id": "safe_ego", "req": "emotional_storm"},
        {"code": "1.9 Б", "id": "controlled_distortion", "req": "emotional_storm"},
    ],
    "Ветка 2: Лучший из Лучших": [
        {"code": "2.1", "id": "remarkable", "req": None},
        {"code": "2.2", "id": "on_the_wave_of_success", "req": "remarkable"},
        {"code": "2.3", "id": "tactical_analysis", "req": "on_the_wave_of_success"},
        {"code": "2.4", "id": "behavior_study", "req": "tactical_analysis"},
        {"code": "2.5", "id": "speech_master", "req": "behavior_study"},
        {"code": "2.6", "id": "pathfinder", "req": "speech_master"},
        {"code": "2.7", "id": "ace_of_all_trades", "req": "pathfinder"},
        {"code": "2.8", "id": "know_your_enemy", "req": "ace_of_all_trades"},
        {"code": "2.9 A", "id": "strategist", "req": "know_your_enemy"},
        {"code": "2.9 Б", "id": "always_ready", "req": "know_your_enemy"},
    ],
    "Ветка 3: Неутомимый": [
        {"code": "3.1", "id": "big_guy", "req": None},
        {"code": "3.2", "id": "defense", "req": "big_guy"},
        {"code": "3.3", "id": "commendable_constitution", "req": "defense"},
        {"code": "3.3опц", "id": "big_heart", "req": "defense"},
        {"code": "3.4", "id": "rock", "req": "commendable_constitution"},
        {"code": "3.5", "id": "despiteAdversities", "req": "rock"},
        {"code": "3.5опц", "id": "heat_resistant", "req": "rock"},
        {"code": "3.6", "id": "adaptation_tireless", "req": "despiteAdversities"},
        {"code": "3.7", "id": "tough_as_steel", "req": "adaptation_tireless"},
        {"code": "3.7опц", "id": "defender", "req": "adaptation_tireless"},
        {"code": "3.8", "id": "survivor", "req": "tough_as_steel"},
        {"code": "3.9", "id": "muscle_overstrain", "req": "survivor"},
        {"code": "3.9опц", "id": "idol_oath", "req": "survivor"},
        {"code": "3.10", "id": "surgeOfStrength", "req": "muscle_overstrain"},
    ],
    "Ветка 4: Медик (Развилка)": [
        {"code": "4.1", "id": "no_hippocratic_oath", "req": None},
        {"code": "4.2 (Good)", "id": "good_as_new", "req": "no_hippocratic_oath"},
        {"code": "4.3 (Good)", "id": "remedy_good", "req": "good_as_new"},
        {"code": "4.4 (Good)", "id": "cheese", "req": "remedy_good"},
        {"code": "4.5 (Good)", "id": "confete", "req": "cheese"},
        {"code": "4.6 (Good)", "id": "you_wont_die_good", "req": "stimulants"},
        {"code": "4.7 (Good)", "id": "careful_neutralization", "req": "you_wont_die_good"},
        {"code": "4.8 (Good)", "id": "doing_good_work", "req": "careful_neutralization"},
        {"code": "4.9 (Good)", "id": "not_today", "req": "doing_good_work"},
        {"code": "4.10 (Good)", "id": "mad_good_doctor", "req": "not_today"},
        {"code": "4.2 (Bad)", "id": "toxicology_weapon", "req": "no_hippocratic_oath"},
        {"code": "4.3 (Bad)", "id": "remedy_bad", "req": "toxicology_weapon"},
        {"code": "4.4 (Bad)", "id": "organ_striking", "req": "remedy_bad"},
        {"code": "4.5 (Bad)", "id": "advanced_toxicology", "req": "organ_striking"},
        {"code": "4.6 (Bad)", "id": "you_wont_die_bad", "req": "advanced_toxicology"},
        {"code": "4.7 (Bad)", "id": "medical_jargon", "req": "you_wont_die_bad"},
        {"code": "4.8 (Bad)", "id": "christmas_tree", "req": "medical_jargon"},
        {"code": "4.9 (Bad)", "id": "insane_zeal", "req": "christmas_tree"},
        {"code": "4.10 (Bad)", "id": "genius_toxicologist", "req": "insane_zeal"},
    ],
    "Ветка 5: Берсерк": [
        {"code": "5.1", "id": "naked_defense", "req": None},
        {"code": "5.2", "id": "vengeful_payback", "req": "naked_defense"},
        {"code": "5.3", "id": "berserker_rage", "req": "vengeful_payback"},
        {"code": "5.3 (Опц)", "id": "naked_defense_2", "req": "vengeful_payback"},
        {"code": "5.4", "id": "calm_mind", "req": "berserker_rage"},
        {"code": "5.5", "id": "frenzy", "req": "calm_mind"},
        {"code": "5.5 (Опц)", "id": "catch_breath", "req": "calm_mind"},
        {"code": "5.6 А (Ярость)", "id": "raging_fury", "req": "frenzy"},
        {"code": "5.6 Б (Сосред.)", "id": "full_concentration", "req": "frenzy"},
        {"code": "5.7", "id": "naked_defense_3", "req": "raging_fury"}, # Или full_concentration (можно дублировать узел с разным req)
        {"code": "5.7 (Опц)", "id": "descending_into_madness", "req": "raging_fury"},
        {"code": "5.8", "id": "steady_hand", "req": "naked_defense_3"},
        {"code": "5.9", "id": "key_moment", "req": "steady_hand"},
        {"code": "5.9 (Опц)", "id": "second_wind_berserk", "req": "steady_hand"},
        {"code": "5.10", "id": "die_hard", "req": "key_moment"},
    ],
    "Ветка 6: Дымовой Эксперт": [
        {"code": "6.1", "id": "hiding_in_smoke", "req": None},
        {"code": "6.2", "id": "smoke_universality", "req": "hiding_in_smoke"},
        {"code": "6.3", "id": "aerial_foot", "req": "smoke_universality"},
        {"code": "6.3 (Опц)", "id": "smoke_screen", "req": "smoke_universality"},
        {"code": "6.4", "id": "recycling", "req": "aerial_foot"},  # Можно привязать к любому 6.3
        {"code": "6.5", "id": "self_preservation", "req": "recycling"},
        {"code": "6.5 (Опц)", "id": "cleansing", "req": "recycling"},
        {"code": "6.6", "id": "experienced_smoker", "req": "self_preservation"},
        {"code": "6.7", "id": "lung_processing", "req": "experienced_smoker"},
        {"code": "6.7 (Опц)", "id": "to_narnia", "req": "experienced_smoker"},
        {"code": "6.8", "id": "smoke_advantage", "req": "lung_processing"},
        {"code": "6.9", "id": "vulnerability_smoke", "req": "smoke_advantage"},
        {"code": "6.9 (Опц)", "id": "thick_smoke", "req": "smoke_advantage"},
        {"code": "6.10", "id": "smoke_and_mirrors", "req": "vulnerability_smoke"},
    ],
    "Ветка 7: Покровитель Удачи": [
        {"code": "7.1", "id": "deal_with_fortune", "req": None},
        {"code": "7.2", "id": "second_chance", "req": "deal_with_fortune"},
        {"code": "7.3", "id": "sequential_luck", "req": "second_chance"},
        {"code": "7.4", "id": "lucky_bastard", "req": "sequential_luck"},
        {"code": "7.5", "id": "not_luck_just_skill", "req": "lucky_bastard"},
        {"code": "7.6", "id": "raise_stakes", "req": "not_luck_just_skill"},
        {"code": "7.7", "id": "azino_777", "req": "raise_stakes"},
        {"code": "7.8", "id": "blessed_by_fate", "req": "azino_777"},
        {"code": "7.9", "id": "ace_sleeve", "req": "blessed_by_fate"},
        {"code": "7.10", "id": "impossible_possible", "req": "ace_sleeve"},
    ],
    "Ветка 8: Военный": [
        {"code": "8.1", "id": "athletic", "req": None},
        {"code": "8.2", "id": "fast_hands", "req": "athletic"},
        {"code": "8.3", "id": "leader", "req": "fast_hands"},
        {"code": "8.4", "id": "addiction_is_a_bitch", "req": "leader"},
        {"code": "8.5", "id": "rapid_retreat", "req": "addiction_is_a_bitch"},
        {"code": "8.6", "id": "combat_reload", "req": "rapid_retreat"},
        {"code": "8.7", "id": "find_vulnerability", "req": "combat_reload"},
        {"code": "8.8", "id": "borrowed_time", "req": "find_vulnerability"},
        {"code": "8.9", "id": "iron_formation", "req": "borrowed_time"},
        {"code": "8.10", "id": "last_hope", "req": "iron_formation"},
    ],
    "Ветка 9: Тень (А) / Кровь (Б)": [
        {"code": "9.1 А", "id": "athleticism_shadow", "req": None},
        {"code": "9.1 Б", "id": "revenge", "req": None},
        {"code": "9.2 А", "id": "not_great_attention", "req": "athleticism_shadow"},
        {"code": "9.2 Б", "id": "formidable_person", "req": "revenge"},
        {"code": "9.3 А", "id": "smashing_blade", "req": "not_great_attention"},
        {"code": "9.3 Б", "id": "slaughter", "req": "formidable_person"},
        {"code": "9.3 (Опц)", "id": "trapmaster", "req": "not_great_attention"},  # Привяжем к А
        {"code": "9.4 А", "id": "fast_and_silent", "req": "smashing_blade"},
        {"code": "9.4 Б", "id": "aggressive_parry", "req": "slaughter"},
        {"code": "9.5 А", "id": "step_into_shadow", "req": "fast_and_silent"},
        {"code": "9.5 Б", "id": "taste_of_victory", "req": "aggressive_parry"},
        {"code": "9.5 (Опц)", "id": "sleight_of_hand", "req": "fast_and_silent"},
        {"code": "9.6 А", "id": "cat_reflexes", "req": "step_into_shadow"},
        {"code": "9.6 Б", "id": "endurance_lessons", "req": "taste_of_victory"},
        {"code": "9.7 А", "id": "eye_for_danger", "req": "cat_reflexes"},
        {"code": "9.7 Б", "id": "cold_blooded", "req": "endurance_lessons"},
        {"code": "9.7 (Опц)", "id": "identity_thief", "req": "cat_reflexes"},
        {"code": "9.8 А", "id": "covering_tracks", "req": "eye_for_danger"},
        {"code": "9.8 Б", "id": "competent_adrenaline", "req": "cold_blooded"},
        {"code": "9.9 А", "id": "knife_in_back", "req": "covering_tracks"},
        {"code": "9.9 Б", "id": "oppression", "req": "competent_adrenaline"},
        {"code": "9.9 (Опц)", "id": "vulnerability_point", "req": "knife_in_back"},
        {"code": "9.10 А", "id": "extreme_measures", "req": "knife_in_back"},
        {"code": "9.10 Б", "id": "butcher", "req": "oppression"},
    ],

    "Ветка 10: Энергия (А) / Идеал (Б)": [
        {"code": "10.1 А", "id": "electrician", "req": None},
        {"code": "10.1 Б", "id": "pain_points", "req": None},
        {"code": "10.2 А", "id": "mechanical_energy", "req": "electrician"},
        {"code": "10.2 Б", "id": "pain_shock", "req": "pain_points"},
        {"code": "10.3 А", "id": "emergency_protection", "req": "mechanical_energy"},
        {"code": "10.3 А (Опц)", "id": "static_electricity", "req": "mechanical_energy"},
        {"code": "10.3 Б", "id": "entering_rhythm", "req": "pain_shock"},
        {"code": "10.3 Б (Опц)", "id": "dirty_tricks", "req": "pain_shock"},
        {"code": "10.4 (Gen)", "id": "playing_on_nerves", "req": "entering_rhythm"},
        {"code": "10.5 А", "id": "overvoltage", "req": "emergency_protection"},
        {"code": "10.5 А (Опц)", "id": "em_field", "req": "emergency_protection"},
        {"code": "10.5 Б", "id": "with_caution", "req": "entering_rhythm"},
        {"code": "10.5 Б (Опц)", "id": "sharp_eye", "req": "entering_rhythm"},
        {"code": "10.6 А", "id": "team_player", "req": "overvoltage"},
        {"code": "10.6 Б", "id": "arrest", "req": "with_caution"},
        {"code": "10.7 А", "id": "battery", "req": "team_player"},
        {"code": "10.7 А (Опц)", "id": "grounding", "req": "team_player"},
        {"code": "10.7 Б", "id": "feint", "req": "arrest"},
        {"code": "10.7 Б (Опц)", "id": "weak_point_energy", "req": "arrest"},
        {"code": "10.8", "id": "rupture_application", "req": "feint"},
        {"code": "10.9 А", "id": "rifting_space", "req": "battery"},
        {"code": "10.9 А (Опц)", "id": "capacitor", "req": "battery"},
        {"code": "10.9 Б", "id": "achilles_heel", "req": "rupture_application"},
        {"code": "10.9 Б (Опц)", "id": "no_mistakes", "req": "rupture_application"},
        {"code": "10.10 А", "id": "short_circuit", "req": "rifting_space"},
        {"code": "10.10 Б", "id": "pride_of_seven", "req": "achilles_heel"},
    ],

    "Ветка 11: Пламя": [
        {"code": "11.1", "id": "strike_iron_hot", "req": None},
        {"code": "11.2", "id": "spark", "req": "strike_iron_hot"},
        {"code": "11.3", "id": "cauterization", "req": "spark"},
        {"code": "11.3 (Опц)", "id": "hot_talent", "req": "spark"},
        {"code": "11.4", "id": "body_adaptation", "req": "cauterization"},
        {"code": "11.5", "id": "hearth_of_power", "req": "body_adaptation"},
        {"code": "11.5 (Опц)", "id": "ashes_to_ashes", "req": "body_adaptation"},
        {"code": "11.6", "id": "hellfire", "req": "hearth_of_power"},
        {"code": "11.7", "id": "wildfire", "req": "hellfire"},
        {"code": "11.7 (Опц)", "id": "fiery_temper", "req": "hellfire"},
        {"code": "11.8", "id": "ifrit", "req": "wildfire"},
        {"code": "11.9", "id": "phoenix", "req": "ifrit"},
        {"code": "11.9 (Опц)", "id": "firestorm", "req": "ifrit"},
        {"code": "11.10", "id": "burn_me_down", "req": "phoenix"},
    ],

    "Ветка 12: Технолог": [
        {"code": "12.1", "id": "projection", "req": None},
        {"code": "12.2", "id": "hacker", "req": "projection"},
        {"code": "12.3", "id": "little_helper", "req": "hacker"},
        {"code": "12.4", "id": "programming_languages", "req": "little_helper"},
        {"code": "12.5", "id": "portable_shield", "req": "programming_languages"},
        {"code": "12.6", "id": "energy_cycle", "req": "portable_shield"},
        {"code": "12.7", "id": "modulation", "req": "energy_cycle"},
        {"code": "12.8", "id": "access_point", "req": "modulation"},
        {"code": "12.9", "id": "error_404", "req": "access_point"},
        {"code": "12.10", "id": "ass_hack", "req": "error_404"},
    ],

    "Ветка 13: Робототехник": [
        {"code": "13.1", "id": "best_friends_forever", "req": None},
        {"code": "13.2", "id": "little_big_trouble", "req": "best_friends_forever"},
        {"code": "13.2 (Опц)", "id": "cell_expander", "req": "little_big_trouble"},
        {"code": "13.3", "id": "no_first_law", "req": "little_big_trouble"},
        {"code": "13.4", "id": "bright_talent", "req": "no_first_law"},
        {"code": "13.5", "id": "smaller_lighter_faster", "req": "bright_talent"},
        {"code": "13.5 (Опц)", "id": "frame_upgrade", "req": "smaller_lighter_faster"},
        {"code": "13.6", "id": "made_to_last", "req": "smaller_lighter_faster"},
        {"code": "13.7", "id": "chimera_core", "req": "made_to_last"},
        {"code": "13.8", "id": "upshot_robot", "req": "chimera_core"},
        {"code": "13.8 (Опц)", "id": "quantum_hub", "req": "upshot_robot"},
        {"code": "13.9", "id": "jack_of_all_trades", "req": "upshot_robot"},
        {"code": "13.10 А", "id": "machina_ex_deo", "req": "jack_of_all_trades"},
        {"code": "13.10 Б", "id": "exogenesis_protocol", "req": "jack_of_all_trades"},
        {"code": "13.10 (Опц)", "id": "multi_connection", "req": "jack_of_all_trades"},
    ],

    "Ветка 14: Тряска (Tremor)": [
        {"code": "14.1", "id": "fight_to_the_end", "req": None},
        {"code": "14.2", "id": "share_with_friend", "req": "fight_to_the_end"},
        {"code": "14.3", "id": "carelessness", "req": "share_with_friend"},
        {"code": "14.4", "id": "pass_the_fare", "req": "carelessness"},
        {"code": "14.5", "id": "own_tremor", "req": "pass_the_fare"},
        {"code": "14.6", "id": "readiness_for_everything", "req": "own_tremor"},
        {"code": "14.7", "id": "keep_going", "req": "readiness_for_everything"},
        {"code": "14.8", "id": "resonance", "req": "keep_going"},
        {"code": "14.9", "id": "immobile", "req": "resonance"},
        {"code": "14.10", "id": "tremor_to_bone", "req": "immobile"},
    ],
    "Связи (Link Talents)": [
        {
            "code": "4+6",
            "id": "censer",
            "req": None,
            "custom_req": [("Ветка 4", 5), ("Ветка 6", 5)]
        },
        {
            "code": "5+3",
            "id": "ardent_defense",
            "req": None,
            "custom_req": [("Ветка 5", 5), ("Ветка 3", 5)]
        },
        {
            "code": "9+12",
            "id": "hitman_assortment",
            "req": None,
            "custom_req": [("Ветка 9", 5), ("Ветка 12", 5)]
        },
        {
            "code": "10+11 A",
            "id": "thermal_energy",
            "req": None,
            "custom_req": [("Ветка 10", 5), ("Ветка 11", 5)]
        },
        {
            "code": "10+11 Б",
            "id": "scorching_mastery",
            "req": None,
            "custom_req": [("Ветка 10", 5), ("Ветка 11", 5)]
        },
    ]
}